"""add pursuit start settings to series

Revision ID: 451e9ead39ea
Revises: 0001_baseline
Create Date: 2026-08-13 15:26:13.852082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '451e9ead39ea'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('pursuit_start_time', sa.String(), nullable=True))
    op.add_column('series', sa.Column('pursuit_distance_nm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'pursuit_distance_nm')
    op.drop_column('series', 'pursuit_start_time')
    # ### end Alembic commands ###
